AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket using CloudFormation

Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref MyS3Bucket, '/*']]