Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket

  ObjectKey:
    Type: String
    Description: Key for the object in the S3 bucket

  LOCALFILEPATH:
    Type: String
    Description: Local path of the file to be uploaded to the S3 bucket
    Default: C:\\Users\\91956\\Desktop\\demo\\s3_bucket.yaml

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  MyObject:
    Type: AWS::S3::BucketObject
    Properties:
      Bucket: !Ref MyS3Bucket
      Key: !Ref ObjectKey
      Source: !Ref LOCALFILEPATH
